<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class SampleJobsSeeder extends Seeder
{
    public function run()
    {
        $jobs = [
            [
                'job_title' => 'Senior PHP Developer',
                'company_name' => 'Tech Solutions Pvt Ltd',
                'job_type' => 'Full-Time',
                'work_mode' => 'Hybrid',
                'job_function' => 'IT & Software',
                'job_location' => 'Mumbai',
                'salary_from' => 800000,
                'salary_to' => 1200000,
                'experience' => '3-5 years',
                'vacancies' => 2,
                'skills' => 'PHP, Laravel, MySQL, JavaScript',
                'description' => 'We are looking for an experienced PHP Developer to join our team.',
                'status' => 'Open',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'job_title' => 'Digital Marketing Executive',
                'company_name' => 'Marketing Pro Agency',
                'job_type' => 'Full-Time',
                'work_mode' => 'On-site',
                'job_function' => 'Marketing',
                'job_location' => 'Delhi',
                'salary_from' => 400000,
                'salary_to' => 600000,
                'experience' => '1-3 years',
                'vacancies' => 3,
                'skills' => 'SEO, Social Media, Content Marketing',
                'description' => 'Join our dynamic marketing team.',
                'status' => 'Open',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'job_title' => 'Frontend Developer Intern',
                'company_name' => 'StartUp Hub',
                'job_type' => 'Internship',
                'work_mode' => 'Remote',
                'job_function' => 'IT & Software',
                'job_location' => 'Bangalore',
                'salary_from' => 180000,
                'salary_to' => 240000,
                'experience' => 'Fresher',
                'vacancies' => 5,
                'skills' => 'HTML, CSS, JavaScript, React',
                'description' => 'Great opportunity for freshers to learn and grow.',
                'status' => 'Open',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'job_title' => 'Sales Manager',
                'company_name' => 'Global Sales Corp',
                'job_type' => 'Full-Time',
                'work_mode' => 'On-site',
                'job_function' => 'Sales',
                'job_location' => 'Pune',
                'salary_from' => 600000,
                'salary_to' => 900000,
                'experience' => '5-10 years',
                'vacancies' => 1,
                'skills' => 'Sales Strategy, Team Management, CRM',
                'description' => 'Lead our sales team to achieve targets.',
                'status' => 'Open',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'job_title' => 'HR Executive',
                'company_name' => 'People First HR',
                'job_type' => 'Part-Time',
                'work_mode' => 'Hybrid',
                'job_function' => 'Human Resources',
                'job_location' => 'Hyderabad',
                'salary_from' => 300000,
                'salary_to' => 450000,
                'experience' => '1-3 years',
                'vacancies' => 2,
                'skills' => 'Recruitment, Employee Relations, HR Policies',
                'description' => 'Handle recruitment and employee engagement.',
                'status' => 'Open',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'job_title' => 'Graphic Designer',
                'company_name' => 'Creative Studio',
                'job_type' => 'Contract',
                'work_mode' => 'Remote',
                'job_function' => 'Design',
                'job_location' => 'Chennai',
                'salary_from' => 350000,
                'salary_to' => 500000,
                'experience' => '1-3 years',
                'vacancies' => 1,
                'skills' => 'Photoshop, Illustrator, Figma, UI/UX',
                'description' => '6-month contract for exciting design projects.',
                'status' => 'Open',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'job_title' => 'Financial Analyst',
                'company_name' => 'Finance Solutions Ltd',
                'job_type' => 'Full-Time',
                'work_mode' => 'On-site',
                'job_function' => 'Finance',
                'job_location' => 'Mumbai',
                'salary_from' => 700000,
                'salary_to' => 1000000,
                'experience' => '3-5 years',
                'vacancies' => 2,
                'skills' => 'Financial Modeling, Excel, SAP, Analysis',
                'description' => 'Analyze financial data and prepare reports.',
                'status' => 'Open',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'job_title' => 'Customer Support Executive',
                'company_name' => 'Support Services Inc',
                'job_type' => 'Full-Time',
                'work_mode' => 'Remote',
                'job_function' => 'Customer Service',
                'job_location' => 'Noida',
                'salary_from' => 250000,
                'salary_to' => 350000,
                'experience' => '0-1 years',
                'vacancies' => 10,
                'skills' => 'Communication, Problem Solving, CRM Tools',
                'description' => 'Provide excellent customer support via phone and email.',
                'status' => 'Open',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        DB::table('managejobs')->insert($jobs);
    }
}
